/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/monster.glb --dry --meta 
Author: SHEEP CODE (https://sketchfab.com/Sheep_Code)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-monster-b9ac7fbf007c4d6d9071c391b055cca2
Title: LOW POLY MONSTER
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/monster.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} userData={{ name: 'Sketchfab_model' }}>
          <group name="61a8424827b64685b2588846bda10618fbx" rotation={[Math.PI / 2, 0, 0]} userData={{ name: '61a8424827b64685b2588846bda10618.fbx' }}>
            <group name="Object_2" userData={{ name: 'Object_2' }}>
              <group name="RootNode" userData={{ name: 'RootNode' }}>
                <group name="corpo001" position={[0, 230, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} userData={{ name: 'corpo.001' }} />
                <group name="Armature" rotation={[-Math.PI / 2, 0, 0]} scale={100} userData={{ name: 'Armature' }}>
                  <group name="Object_6" userData={{ name: 'Object_6' }}>
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_8" position={[0, 230, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} userData={{ name: 'Object_8' }} />
                    <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.Material} skeleton={nodes.Object_9.skeleton} userData={{ name: 'Object_9' }} />
                    <skinnedMesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials['Material.001']} skeleton={nodes.Object_10.skeleton} userData={{ name: 'Object_10' }} />
                    <skinnedMesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.preto} skeleton={nodes.Object_11.skeleton} userData={{ name: 'Object_11' }} />
                    <skinnedMesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.branco} skeleton={nodes.Object_12.skeleton} userData={{ name: 'Object_12' }} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/monster.glb')
